### ISSUE TITLE
Shaders in `Shadow Maps` example fails to compile: `unresolved value 'align'`

### ISSUE THREAD

**Issue by ErichDonGubler** [shi-yan/WebGPUTutorial#1]
From my current console log in `Chrome Version 127.0.6533.89 (Official Build) (arm64)`:

```
about:srcdoc:1 Error while parsing WGSL: :105:17 error: unresolved value 'align'
            if (align > 0.9) {
                ^^^^^


 - While validating [ShaderModuleDescriptor]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).
```

**Comment by shi-yan** [comment]
Thank you very much for reporting it. I had mistakenly removed a line. just added it back

Please check again! Thank you!

https://shi-yan.github.io/webgpuunleashed/code/code.html#5_01_shadow_maps
